### ISSUE TITLE
Getting errors even after added project name and version name in the workflow

### ISSUE THREAD

**Issue by HiteshDevaram-Philips** [philips-labs/blackduck-scanner-action#13]
Hi,

Thanks for your action but i am getting few errors even after adding project name and version name from Blackduck.
Here are the errors i got it  when i execute my workflow:
i have passed my details as:
       blackduck-url: https://blackduck.philips.com/
       blackduck-token: ${{ secrets.BLACKDUCK_TOKEN_HTH }}
       project: ES_saas-factory-edi-apigateway
       version: saas-factory-edi-apigateway

and the errors are:

+ getting project api base url
/get-blackduck-report.sh: line 34: [: null: integer expression expected
| got project api base url: null

+ getting version api base url
/get-blackduck-report.sh: line 46: [: -eq: unary operator expected
| got version api base url: 

+ creating SBOM report
| triggered creating SBOM report

+ getting SBOM report api base url
| attempt 1 of 50 to get SDPX report
 ERROR: report_status is not COMPLETED, it is .
| - report_status: 
##[debug]Docker Action run completed with exit code 1

**Comment by JeroenKnoops** [comment]
This is an issue in : https://github.com/philips-software/blackduck-report-action
